source 'https://rubygems.org'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22.0'
end

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'rubocop-rspec', '~> 2.26'
end
